---

- name: Ensure /etc/kamailio exists
  file: path=/etc/kamailio state=directory

- name: Copy kamailio config
  template: src=kamailio.cfg.j2 dest=/etc/kamailio/kamailio.cfg

- name: Ensure /etc/keepalived exists
  file: path=/etc/keepalived state=directory

- name: Template keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf