- name: Spin up a cluster of CoreOS boxen.
  hosts: libvirthost
  vars_files:
    - ["vars/private.yml", "vars/coreos.yml"]
  vars:
    # now in files!
  sudo: true
  pre_tasks:
    # I role-ized it.
  roles:
    - { role: get-etcd-token }
    - { role: libvirt-coreos, mode: create, boxnumber: 5, box_role: controller }
    - { role: libvirt-coreos, mode: create, boxnumber: 0, box_role: kamailio }
    - { role: libvirt-coreos, mode: create, boxnumber: 1, box_role: kamailio }
    - { role: libvirt-coreos, mode: create, boxnumber: 2, box_role: asterisk }
    - { role: libvirt-coreos, mode: create, boxnumber: 3, box_role: asterisk }
    - { role: libvirt-coreos, mode: create, boxnumber: 4, box_role: homer }

    # - { include: tasks/libvirt_spinup.yml, boxnumber: 0 }
    # - { include: tasks/libvirt_spinup.yml, boxnumber: 1 }
    # - { include: tasks/libvirt_spinup.yml, boxnumber: 2 }
