---
- name: Preparing RTPProxy
    
  hosts: rtpproxy1
  vars:
    base_dir: /usr/local/src/RTPProxy
    aws_env:
        AWS_ACCESS_KEY_ID: AKIAINWPBS3CZESKN7KQ   ### Valut
        AWS_SECRET_ACCESS_KEY: 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   ### Valut
  become: true

  tasks:

  - name: Importing Infrastructure network variables
    include_vars:
        file: environment_variables/network.yml
        name: ips

  - name: Importing rtpproxy variables
    include_vars:
        file: environment_variables/rtpproxy.yml
        name: rtp

  - name: Insure the Host state for pre-requests packages
    apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
        allow_unauthenticated: yes
    with_items:
         - git
         - docker.io
         - tree
         - tmux
         - python-pip
    become: true

  - name: Install aws cli
    pip:
        name: awscli

  - name: Configure git helpers to codecommit
    git_config:
        name: credential.UseHttpPath
        value: true
        scope: global
  - name: Configure git helpers to codecommit
    git_config:
        name: credential.helper
        value: '!aws codecommit credential-helper $@'
        scope: global

  - name: Insure the docker-compose state
    get_url:
        url: https://github.com/docker/compose/releases/download/1.15.0/docker-compose-Linux-x86_64
        dest: /sbin/docker-compose
        mode: 0555

  - name: Clone lastest configuration
    git:
        repo: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/cpaas.rtpproxy
        dest: "{{ base_dir }}"
        update: no
    register: config_updated
    environment: "{{aws_env}}"
    become: true


  - name: Building the docker-compose.yml from vars
    copy:
        src: files/rtpproxy.docker-compose.yml
        dest: "{{ base_dir }}/docker-compose.yml"

  - name: Building run.sh 
    template:
        src: templates/rtpproxy.run.sh.j2
        dest: "{{ base_dir }}/docker/run.sh"

