---
# A set of actions for spinning up coreos boxes with libvirt.
# Requires a series of variables, defined at the beginning of tasks here.
# Otherwise takes these modes:
# mode == "create"     --> create a box with boxnumber
# mode == "rediscover" --> rediscover boxes with new etcd discovery token.

    - name: Fail if boxnumber is not defined
      fail: msg="This role requires 'boxnumber' as a variable"
      when: boxnumber is not defined

    - name: Set vm_name every time
      set_fact:
          vm_name: "coreos{{ boxnumber }}"

    - name: Fail if libvirt_subnet is not defined
      fail: msg="This role requires 'libvirt_subnet' as a variable"
      when: libvirt_subnet is not defined

    - name: Fail if coreos_discovery is not defined
      fail: msg="This role requires 'coreos_discovery' as a variable"
      when: coreos_discovery is not defined

    - name: Destroy in destroy mode
      set_fact:
          destroy: True
      when: mode == 'destroy'

    - { include: libvirt_spinup.yml, when: mode == 'create' }
    - { include: libvirt_reloaduserdata.yml, when: mode == 'rediscover' }
    - { include: libvirt_shutdown.yml, when: mode == 'destroy' }
    - { include: libvirt_loaduserdata.yml, when: mode == 'userdata'}